import assert from 'node:assert/strict'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] })
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, timezoneId: 'Asia/Shanghai' })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
const baseUrl = process.env.TEST_BASE_URL || 'http://127.0.0.1:5173'
const date = new Intl.DateTimeFormat('sv-SE', { timeZone: 'Asia/Shanghai' }).format(new Date())
const planText = '@run=测试工作流\n@task Task {\n@event Event {\n{ hello }\n}\n}'
const base = { owner: 'owner-1', planText, status: 'succeeded', requestedAction: 'none', familyId: 'family', versionNumber: 1, versionMajor: 1, versionMinor: 0, origin: 'initial', executionMode: 'serial', scheduledAt: '', totalTasks: 2, completedTasks: 2, created: '2026-09-26T14:00:00Z', updated: '2026-09-26T14:00:00Z' }
const runs = Array.from({ length: 25 }, (_, index) => ({ ...base, id: `run-${index}`, title: index === 0 ? `工作流 ${date} #009` : index === 1 ? '计算机网络复习' : `每日整理 ${index}`, status: index === 2 ? 'failed' : index === 3 ? 'canceled' : index === 4 ? 'running' : index === 5 ? 'draft' : 'succeeded' }))
const versions = Array.from({ length: 35 }, (_, index) => ({ ...base, id: `version-${index + 1}`, title: `知识点总结 ${index + 1}`, versionNumber: index + 1, versionMajor: index + 1 }))
const requests = []
await context.addInitScript(() => localStorage.setItem('anyworkflow.auth.session.v1', JSON.stringify({ token: 'fixture-token', record: { id: 'owner-1', email: 'test@example.invalid' }, baseUrl: 'https://pb.example.invalid' })))
await context.route('https://pb.example.invalid/**', async route => {
  assert.equal(route.request().method(), 'GET', 'browsing and automatic naming must never write records')
  const url = new URL(route.request().url())
  requests.push(url)
  const collection = url.pathname.split('/')[3]
  const id = url.pathname.split('/')[5]
  if (collection === 'aw_dispatch_runs' && id) return route.fulfill({ json: [...runs, ...versions].find(run => run.id === id) })
  let items = collection === 'aw_dispatch_runs' ? [...runs] : []
  const filter = url.searchParams.get('filter') || ''
  if (filter.includes('familyId=')) items = [...versions]
  const statuses = [...filter.matchAll(/status="([^"]+)"/g)].map(match => match[1])
  if (statuses.length) items = items.filter(run => statuses.includes(run.status))
  const search = filter.match(/title~"([^"]+)"/)?.[1]
  if (search) items = items.filter(run => run.title.includes(search) || run.id === search)
  const pageNumber = Number(url.searchParams.get('page') || 1)
  const perPage = Number(url.searchParams.get('perPage') || 20)
  await route.fulfill({ json: { page: pageNumber, perPage, totalItems: items.length, totalPages: Math.ceil(items.length / perPage), items: items.slice((pageNumber - 1) * perPage, pageNumber * perPage) } })
})
try {
  await page.goto(baseUrl)
  await page.getByRole('link', { name: '计算机网络复习', exact: true }).waitFor()
  assert.equal(await page.getByRole('tab').count(), 6)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `overflow ${width}`)
    if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/dashboard-${width}.png`, fullPage: true })
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '下一页', exact: true }).click()
  await page.waitForURL(/page=2/)
  await page.getByRole('searchbox', { name: '搜索工作流' }).fill('网络')
  await page.waitForURL(url => url.searchParams.get('q') === '网络')
  await page.getByRole('link', { name: '计算机网络复习', exact: true }).waitFor()
  assert.equal(new URL(page.url()).searchParams.get('page'), null)
  assert.equal(await page.locator('article').count(), 1)
  await page.reload()
  assert.equal(await page.getByRole('searchbox', { name: '搜索工作流' }).inputValue(), '网络')
  await page.getByRole('searchbox', { name: '搜索工作流' }).fill('x'.repeat(200))
  await page.getByText('没有找到匹配的工作流', { exact: true }).waitFor()
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'long search terms cannot overflow')
  await page.getByRole('button', { name: '清除搜索' }).first().click()
  await page.getByRole('tab', { name: '失败', exact: true }).click()
  await page.getByRole('link', { name: '每日整理 2', exact: true }).waitFor()
  assert.equal(await page.locator('article').count(), 1)
  await page.getByRole('tab', { name: '取消', exact: true }).click()
  await page.getByRole('link', { name: '每日整理 3', exact: true }).waitFor()
  assert.equal(await page.locator('article').count(), 1)
  await page.getByRole('button', { name: '操作 每日整理 3' }).click()
  await page.getByRole('dialog').waitFor()
  await page.keyboard.press('Escape')
  await page.goto(`${baseUrl}/runs/version-10`)
  await page.getByRole('button', { name: '选择 Run 版本' }).click()
  await page.getByRole('textbox', { name: '搜索版本' }).fill('v20.0')
  await page.getByRole('button', { name: /v20.0 知识点总结/ }).click()
  await page.getByRole('heading', { name: '知识点总结 20', exact: true }).waitFor()
  assert.ok(page.url().endsWith('/runs/version-10'), 'version switching preserves the route')
  await page.getByRole('button', { name: '下一个版本' }).click()
  await page.getByRole('heading', { name: '知识点总结 21', exact: true }).waitFor()
  await page.getByRole('button', { name: '选择 Run 版本' }).click()
  if (process.env.SCREENSHOT_DIR) await page.screenshot({ path: `${process.env.SCREENSHOT_DIR}/versions-mobile.png` })
  await page.getByRole('button', { name: '查看最新版本 v35.0' }).click()
  await page.getByRole('heading', { name: '知识点总结 35', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: '下一个版本' }).isDisabled(), true)
  await page.goto(`${baseUrl}/runs/new`)
  await page.getByRole('heading', { name: `工作流 ${date} #010`, exact: true }).waitFor()
  const another = await context.newPage()
  await another.goto(`${baseUrl}/runs/new`)
  await another.getByRole('heading', { name: `工作流 ${date} #011`, exact: true }).waitFor()
  await another.close()
  const parallel = await Promise.all([context.newPage(), context.newPage()])
  await Promise.all(parallel.map(tab => tab.goto(`${baseUrl}/runs/new`)))
  await Promise.all(parallel.map(tab => tab.getByRole('heading', { name: /工作流 .* #01[23]/ }).waitFor()))
  const names = await Promise.all(parallel.map(tab => tab.locator('h1').innerText()))
  assert.deepEqual(names.sort(), [`工作流 ${date} #012`, `工作流 ${date} #013`])
  await Promise.all(parallel.map(tab => tab.close()))
  await page.locator('.cm-content').click()
  await page.keyboard.press('ControlOrMeta+a')
  await page.keyboard.insertText(planText + '\n# 离线恢复草稿')
  await page.waitForTimeout(600)
  await page.route('https://pb.example.invalid/**', route => route.abort())
  await page.reload()
  await page.getByRole('button', { name: '恢复', exact: true }).click()
  assert.ok((await page.locator('.cm-content').innerText()).includes('离线恢复草稿'))
  assert.deepEqual(errors, [])
  console.log('PASS: responsive dashboard, search/pagination/reload, failed/canceled filters, actions, 35-version search/next/latest, date naming and cross-tab reservation')
} finally { await browser.close() }
